## NumPy Indexing and Selection

In [21]:
import numpy as np

In [22]:
arr = np.arange(0,17)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Bracket Indexing and Selection

In [23]:
arr[5]

5

In [24]:
arr[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

### Indexing a 2D array (matrices)

using one subscript comma approach i.e. **arr_2d[row,col]**. 

In [25]:
arr_2d = np.array(([3,6,9],[10,15,20],[20,25,30],[90,67,56]))
arr_2d

array([[ 3,  6,  9],
       [10, 15, 20],
       [20, 25, 30],
       [90, 67, 56]])

In [26]:
arr_2d[2]

array([20, 25, 30])

In [27]:
#Indexing multiple rows
arr_2d[2:4]

array([[20, 25, 30],
       [90, 67, 56]])

In [28]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[2,0]

20

In [29]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 6,  9],
       [15, 20]])

In [30]:
#Shape bottom row
arr_2d[2:5,4:7]

array([], shape=(2, 0), dtype=int64)

## Quiz 5 

What will the output of follwoing lines of code?

arr_2d = np.arange(16).reshape(4,4)
arr_2d[2:4][1:2]

* array( [[ 8,  9, 10, 11],
       [12, 13, 14, 15]] )
* array( [[12, 13, 14, 15]] )
* array([], shape=(0, 4), dtype=int64)
* None of these

### Selection

Selecting/Filtering data based on some conditions.

In [31]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
arr1 > 7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
bool1 = arr>7

In [34]:
bool1

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [35]:
arr1[arr1>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
arr1[arr1==12]

array([12])

In [38]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### np.where() function

syntax - **numpy.where(condition[, x, y])**

* It returns the indices of elements in an input array where the given condition is satisfied.

* If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [39]:
np.where(arr1>7) #indices

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)

In [40]:
arr1[np.where(arr1>7)] #values

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
# case 2
np.where(arr1>7, arr1, 1)

array([ 1,  1,  1,  1,  1,  1,  1,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])