# NumPy 

#### Installing NumPy 

In [2]:
#!pip install numpy

#### Importing NumPy

In [3]:
import numpy as np

## Why Numpy?

#### case 1 - Easy Operations

In [2]:
list1 = list(range(1,100,5))
print(list1)
for i in range(len(list1)):
    list1[i]=list1[i]+5
print(list1)

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]
[6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, 101]


In [3]:
arr1 = np.arange(1,100,5)
print(arr1)
arr1 = arr1+5
print(arr1)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[  6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91
  96 101]


#### case 2 - Speed

In [4]:
import random

In [2]:
%%time
for j in range(1000):
    list1 = list(range(1,1000,3))
    #print(list1)
    list2 = list(range(2,1001,3))
    #print(list2)
    #list1 + list2
    list3 = []
    for i in range(len(list1)):
        list3.append(list1[i]+list2[i])
#print(list3)

Wall time: 88.9 ms


In [3]:
%%time
for x in range(1000):
    a = np.arange(1,1000,3)
    b = np.arange(2,1001,3)
    c = a+b

Wall time: 4 ms


#### case 3 - Memory

In [13]:
import sys

python_list = [10,20,30,40,50,60,70]
numpy_array = np.array([10,20,30,40,50,60,70])

sizeof_python_list = sys.getsizeof(1) * len(python_list)      # 28 bytes     
sizeof_numpy_array = numpy_array.itemsize * numpy_array.size    # default 8 bytes 
print("Size of Python list", sizeof_python_list)
print("Size of NumPy Array", sizeof_numpy_array)

Size of Python list 196
Size of NumPy Array 56



## Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

### Various ways to create NumPy Arrays

#### 1. From a normal Python List

We can create a Numpy array by directly converting a list or list of lists:

In [7]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [8]:
np.array(list1)

array([10, 20, 30])

In [15]:
matrix1 = [[10,20,30],[40,50,60],[70,80,90]]
matrix1

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [16]:
np.array(matrix1)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
np.matrix(matrix1) #NOT recommended

matrix([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

#### 2. Using Built-in Methods

There are many built-in methods to generate Numpy Arrays.

### a. arange

Returns a range of values for the specified interval.

In [11]:
np.arange(0,18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [12]:
np.arange(10,99,5)  #1st argument- start value, 2nd argument - end value(exclusive), 3rd argument - step size                                                                                                       

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [13]:
np.arange(19,1,-2)

array([19, 17, 15, 13, 11,  9,  7,  5,  3])

In [14]:
np.arange(1,18,-2)

array([], dtype=int32)

In [15]:
np.arange(-18,1, -1)

array([], dtype=int32)

In [45]:
np.arange(1,4,1)

array([1, 2, 3])

### Quiz 2

What would be the output of following code?

**np.arange(-1,4,1)**

* array( [-1,  0,  1,  2,  3] )
* array([ ], dtype=int64)
* array( [-1, -2, -3] )
* array( [1, 2, 3] )

### b. zeros and ones

Generate arrays of zeros or ones.

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((4,4)) #argument is a tuple, in tuple we need to specify number of rows and columns 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### c. linspace
Returns evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,10,3) #3rd argument for total numbers to be generated.

array([ 0.,  5., 10.])

In [21]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [22]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

### d. eye

Creates an identity matrix

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 3. Generating Random number arrays

Numpy also has many inbuilt functions to generate random number arrays:

#### a. rand
Generates uniformly distributed random numbers over ``[0, 1)``.

In [24]:
np.random.rand(5)

array([0.19564877, 0.41490021, 0.37050422, 0.11251901, 0.28709207])

In [25]:
np.random.rand(4,4)

array([[0.82772807, 0.45131765, 0.01247243, 0.87079271],
       [0.06879543, 0.07867226, 0.39961691, 0.0794265 ],
       [0.79577955, 0.15847733, 0.06292424, 0.78530547],
       [0.47968839, 0.35536984, 0.30447615, 0.93332018]])

### randn

Generates normally distributed(standard normal distribution) random numbers.

In [26]:
np.random.randn(4)

array([1.93867569, 1.47223573, 0.47307282, 0.65885309])

In [27]:
np.random.randn(4,4)

array([[-0.48860555, -0.12883783,  0.56545503,  1.44849604],
       [-1.23976792,  0.7301841 ,  0.80641129, -2.05791058],
       [ 0.90812787,  1.39440064, -0.34220335,  1.5303514 ],
       [ 2.17957461,  0.55878655,  1.15844625, -1.03378454]])

### randint
Generates random integers over given range.

In [28]:
np.random.randint(12,100)

77

In [29]:
np.random.randint(12,100,9) #3rd argument for total numbers to be generated.

array([37, 37, 32, 75, 83, 29, 38, 33, 24])

## Quiz 3

Which of the following(s) has the ability to generate 4 numbers ranging from 2 to 8?

* np.linspace(2,8,4)
* np.random.randint(2,8,4)
* np.random.randint(2,9,4)
* np.linspace(2,9,4)

### Array Attributes and Methods

In [22]:
array1 = np.arange(20)
randomarray1 = np.random.randint(0,50,10)

In [23]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
array1.shape

(20,)

In [25]:
randomarray1

array([11, 28,  2, 46, 32, 23, 37, 11,  4, 31])

## Reshape
change the original shape(dimension) of the array.

In [26]:
arr1 =array1.reshape(4,5)

In [27]:
arr1.shape[1]

5

## Quiz 4

Which of the following(s) reshape operations are possible on the array

**ar = np.arange(8)**

* ar.reshape(2,4)
* ar.reshape(4,2)
* ar.reshape(1,-1)
* ar.reshape(8,-1)


### max,min,argmax,argmin

max(), min() for finding minimum and maximum value.
argmax(),argmin() for index of min and max elements.

In [36]:
randomarray1

array([46, 10, 18, 29, 25, 18,  4,  1, 44, 39])

In [37]:
randomarray1.max()

46

In [38]:
randomarray1.argmax()

0

In [39]:
randomarray1.min()

1

In [40]:
randomarray1.argmin()

7

## Shape

Shape is an attribute that denotes dimension(shape) of array.

In [41]:
# Vector
array1.shape

(20,)

In [42]:
# Notice the two sets of brackets
array1.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [43]:
array1.reshape(1,20).shape

(1, 20)

In [44]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
array1.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [46]:
array1.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

### dtype

To get the data type of the object in the array:
* similar method : np.result_type()

In [31]:
array1.dtype

dtype('int64')

In [32]:
np.result_type(array1)

dtype('int64')

In [33]:
array2 = np.arange(0, 10, 1.33,dtype=np.int32)
array2

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [34]:
array3 = np.arange(0, 10, 2,dtype=np.float64)
array3

array([0., 2., 4., 6., 8.])

#### type 
type() returns class type of an object.

In [35]:
type(array1)

numpy.ndarray

In [36]:
type(array2)

numpy.ndarray