## NumPy Operations

### Arithmetic
Basic arithmetic operations: +,-,*,/,%.
Can be performed like array with array arithmetic, or scalar with array arithmetic.

In [5]:
import numpy as np
arr = np.arange(0,5)

In [6]:
arr + arr

array([0, 2, 4, 6, 8])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16])

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
# Warning on division by zero
# divison by zero replaced with nan
arr/arr

<ipython-input-9-0c3471267e38>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.])

In [10]:
arr**3

array([ 0,  1,  8, 27, 64])

### Some universal Array Functions

In [16]:
np.sort(arr)

array([0, 1, 2, 3, 4])

In [11]:
#for Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [12]:
#for exponential (e^)
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [13]:
np.max(arr) #same as arr.max()

4

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [15]:
np.log(arr)

<ipython-input-15-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])